export const CONTRACT_VERSION = "2026.03.11";

export const MCP_PRIMARY_VERBS = Object.freeze([
  "search",
  "context.query",
  "fix",
  "research",
  "read",
  "explore",
  "grep",
  "search_code",
  "remember",
  "record",
  "learn",
  "share_context",
]);

// MCP server currently exposes this concrete runtime tool set.
// The registry keeps historical/compat tool names for documentation and client
// compatibility, but contract parity checks should assert only against what is
// actually reachable via the running MCP server.
const MCP_RUNTIME_TOOLSET = Object.freeze([
  "context",
  "remember",
  "forget",
  "compress",
  "index",
  "search",
  "grep",
  "read",
]);

export const CONTRACT_METADATA = Object.freeze({
  contract_version: CONTRACT_VERSION,
  status: "ga",
  migration_window_days: 90,
  deprecation_clock_starts: "contract-registry-ga",
  removal_policy: "first-major-after-window",
  sdk_legacy: {
    deprecated_symbol: "WhisperContext",
    deprecated_in: "v3",
    removed_in: "v4",
  },
  mcp_primary_verbs: MCP_PRIMARY_VERBS,
  ignored_http_prefixes: [
    "/v1/wizard/",
    "/v1/admin/",
    "/v1/billing/",
    "/v1/usage",
    "/v1/org",
    "/v1/keys",
    "/v1/jobs/",
    "/v1/sync-jobs/",
    "/v1/webhooks",
    "/v1/conversations",
    "/v1/projects/resolve",
    "/v1/projects/:id/stats",
    "/v1/projects/:projectId/add_source",
    "/v1/projects/:projectId/sources/github-tarball",
    "/v1/sources",
    "/v1/sources/:sourceId",
    "/v1/entities",
    "/v1/relations",
    "/v1/graph/",
  ],
});

const DEFAULT_ERROR_SCHEMA = Object.freeze({
  type: "object",
  required: ["success", "error", "trace_id"],
  properties: {
    success: "boolean",
    error: {
      code: "string",
      message: "string",
      details: "string?",
    },
    trace_id: "string",
  },
});

const SECURITY_DEFAULTS = Object.freeze({
  retrieval: {
    auth_type: "api_key",
    tenant_scope: "project",
    user_scope: "optional",
    sensitive_input_class: "medium",
    sensitive_output_class: "medium",
    log_redaction_policy: "standard",
    abuse_profile: "query",
    local_filesystem_risk: "none",
    audit_required: false,
    destructive: false,
    high_risk: false,
  },
  memory_write: {
    auth_type: "api_key",
    tenant_scope: "project",
    user_scope: "optional",
    sensitive_input_class: "high",
    sensitive_output_class: "medium",
    log_redaction_policy: "strict",
    abuse_profile: "mutation",
    local_filesystem_risk: "none",
    audit_required: true,
    destructive: false,
    high_risk: false,
  },
  session_capture: {
    auth_type: "api_key",
    tenant_scope: "project",
    user_scope: "session",
    sensitive_input_class: "high",
    sensitive_output_class: "medium",
    log_redaction_policy: "strict",
    abuse_profile: "mutation",
    local_filesystem_risk: "none",
    audit_required: true,
    destructive: false,
    high_risk: false,
  },
  knowledge_ingest: {
    auth_type: "api_key",
    tenant_scope: "project",
    user_scope: "none",
    sensitive_input_class: "high",
    sensitive_output_class: "low",
    log_redaction_policy: "strict",
    abuse_profile: "ingest",
    local_filesystem_risk: "possible",
    audit_required: true,
    destructive: false,
    high_risk: false,
  },
  share_export: {
    auth_type: "api_key",
    tenant_scope: "project",
    user_scope: "session",
    sensitive_input_class: "high",
    sensitive_output_class: "high",
    log_redaction_policy: "strict",
    abuse_profile: "mutation",
    local_filesystem_risk: "none",
    audit_required: true,
    destructive: false,
    high_risk: true,
  },
  delete_admin: {
    auth_type: "api_key",
    tenant_scope: "cross-tenant-sensitive",
    user_scope: "optional",
    sensitive_input_class: "high",
    sensitive_output_class: "low",
    log_redaction_policy: "strict",
    abuse_profile: "mutation",
    local_filesystem_risk: "possible",
    audit_required: true,
    destructive: true,
    high_risk: true,
  },
});

function makeSecurityChecklist(profile, overrides = {}) {
  return {
    profile,
    ...SECURITY_DEFAULTS[profile],
    ...overrides,
  };
}

function defineOperation({
  id,
  status = "ga",
  request_schema,
  response_schema,
  error_schema = DEFAULT_ERROR_SCHEMA,
  auth,
  privacy,
  rate_limit_profile,
  deprecation,
  security_profile,
  security_overrides,
  surfaces,
}) {
  return {
    id,
    version: CONTRACT_VERSION,
    status,
    request_schema,
    response_schema,
    error_schema,
    auth,
    privacy,
    rate_limit_profile,
    deprecation: deprecation || {
      status: "none",
      replacement: null,
      removal_after_days: CONTRACT_METADATA.migration_window_days,
    },
    surfaces,
    security_checklist: makeSecurityChecklist(security_profile, security_overrides),
  };
}

export const CONTRACT_REGISTRY = Object.freeze([
  defineOperation({
    id: "memory.search",
    request_schema: {
      type: "object",
      description: "Canonical memory retrieval entry used as the reference specimen for contract-first design.",
      required: [],
      properties: {
        id: "string?",
        query: "string?",
        project: "string?",
        scope: "personal|shared_project?",
        user_id: "string?",
        session_id: "string?",
        top_k: "number?",
        profile: "fast|balanced|quality?",
        include_pending: "boolean?",
      },
      validation: [
        "At least one of id or query must be present.",
        "If id is present, exact fetch is performed.",
        "If query is present, semantic retrieval is performed.",
        "If id and query are both present, the exact fetch is returned and query may be used for related context.",
      ],
    },
    response_schema: {
      type: "object",
      properties: {
        memory: "object?",
        results: "array?",
        count: "number",
        mode: "exact|semantic|hybrid",
        include_pending: "boolean?",
        pending_overlay_count: "number?",
      },
    },
    auth: {
      type: "api_key",
      scopes: ["read"],
      tenant_scope: "project",
    },
    privacy: {
      classification: "customer-memory",
      input_sensitivity: "high",
      output_sensitivity: "high",
      logging: "redacted",
    },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    security_overrides: {
      user_scope: "optional",
      sensitive_output_class: "high",
      audit_required: true,
    },
    surfaces: {
      http: [
        { method: "POST", route: "/v1/memory/search", status: "canonical" },
        { method: "GET", route: "/v1/memory/:memoryId", status: "canonical" },
        { method: "POST", route: "/v1/memories/search", status: "compat", replacement: "/v1/memory/search" },
        { method: "GET", route: "/v1/memories/:id", status: "compat", replacement: "/v1/memory/:memoryId" },
      ],
      sdk: [
        { binding: "WhisperContext.searchMemories", token: "searchMemories(" },
        { binding: "WhisperContext.getMemory", token: "getMemory(memoryId" },
        { binding: "WhisperClient.memory.search", token: "search: (params) => this.memoryModule.search(params)" },
        { binding: "WhisperClient.memory.get", token: "get: (memoryId) => this.memoryModule.get(memoryId)" },
      ],
      mcp_primary: [
        { tool: "search", mode: "semantic" },
        { tool: "search", mode: "exact" },
      ],
      mcp_compat: [
        { tool: "memory.search" },
      ],
    },
  }),
  defineOperation({
    id: "context.query",
    request_schema: {
      type: "object",
      properties: {
        project: "string?",
        query: "string",
        path: "string?",
        top_k: "number?",
        chunk_types: "array?",
        include_memories: "boolean?",
        include_graph: "boolean?",
        user_id: "string?",
        session_id: "string?",
        max_tokens: "number?",
      },
    },
    response_schema: {
      type: "object",
      properties: {
        results: "array?",
        evidence: "array?",
        context: "string?",
        meta: "object?",
        diagnostics: "object?",
        retrieval_route: "string?",
        retrieval_readiness: "string?",
        semantic_status: "ok|adaptive|failed?",
        fallback_mode: "none|adaptive_threshold|lexical_rescue|lexical_backend?",
        recommended_fixes: "array?",
        status_label: "healthy|degraded_auto_repairing|needs_user_action|blocked?",
        status_action: "none|run_auto_repair|restart_client|reauth|add_source|reindex?",
        action_required: "boolean?",
        warnings: "array?",
        recommended_next_calls: "array?",
        workspace_id: "string?",
        root_path: "string?",
      },
    },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "knowledge-base", input_sensitivity: "medium", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: {
      http: [{ method: "POST", route: "/v1/context/query", status: "canonical" }],
      sdk: [{ binding: "WhisperContext.query", token: "async query(params" }],
      mcp_primary: [{ tool: "context.query", mode: "canonical_retrieval" }, { tool: "search", mode: "semantic_context" }],
      mcp_compat: [{ tool: "context.get_relevant" }, { tool: "context" }],
    },
  }),
  defineOperation({
    id: "memory.add",
    request_schema: {
      type: "object",
      description: "Canonical durable memory write entry for `remember`. Use this when the agent wants a fact, preference, instruction, or decision to persist beyond the current turn.",
      required: ["content"],
      properties: {
        project: "string?",
        content: "string",
        memory_type: "factual|preference|event|relationship|opinion|goal|instruction?",
        scope: "personal|shared_project?",
        user_id: "string?",
        session_id: "string?",
        agent_id: "string?",
        importance: "number?",
        metadata: "object?",
      },
      validation: [
        "content must be a non-empty string.",
        "memory_type defaults to factual when omitted.",
        "importance must be between 0 and 1 when provided.",
        "This operation is for durable memory writes only; use memory.ingest_session / record for conversational capture.",
      ],
    },
    response_schema: {
      type: "object",
      properties: {
        success: "boolean",
        id: "string?",
        memory: "object?",
        queued: "boolean?",
        write_mode: "sync|async?",
      },
    },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: {
      classification: "customer-memory",
      input_sensitivity: "high",
      output_sensitivity: "medium",
      logging: "redacted",
    },
    rate_limit_profile: "mutation",
    security_profile: "memory_write",
    security_overrides: {
      user_scope: "optional",
      audit_required: true,
      sensitive_input_class: "high",
    },
    surfaces: {
      http: [
        { method: "POST", route: "/v1/memory", status: "canonical" },
        { method: "POST", route: "/v1/memories", status: "compat", replacement: "/v1/memory" },
      ],
      sdk: [
        { binding: "WhisperContext.addMemory", token: "async addMemory(params" },
        { binding: "WhisperClient.memory.add", token: "add: (params) => this.memoryModule.add(params)" },
      ],
      mcp_primary: [{ tool: "remember" }],
      mcp_compat: [{ tool: "memory.add" }],
    },
  }),
  defineOperation({
    id: "memory.ingest_session",
    request_schema: { type: "object", properties: { project: "string?", session_id: "string", messages: "array" } },
    response_schema: { type: "object", properties: { memories_created: "number", relations_created: "number" } },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: { classification: "session-capture", input_sensitivity: "high", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "ingest",
    security_profile: "session_capture",
    surfaces: {
      http: [{ method: "POST", route: "/v1/memory/ingest/session", status: "canonical" }],
      sdk: [{ binding: "WhisperContext.ingestSession", token: "async ingestSession(params" }],
      mcp_primary: [{ tool: "record" }],
      mcp_compat: [{ tool: "memory.ingest_conversation" }, { tool: "compress" }],
    },
  }),
  defineOperation({
    id: "memory.bulk_write",
    request_schema: { type: "object", properties: { project: "string", memories: "array" } },
    response_schema: { type: "object", properties: { success: "boolean", job_id: "string?" } },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: { classification: "customer-memory", input_sensitivity: "high", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "ingest",
    security_profile: "memory_write",
    surfaces: {
      http: [{ method: "POST", route: "/v1/memory/bulk", status: "canonical" }],
      sdk: [
        { binding: "WhisperContext.addMemoriesBulk", token: "async addMemoriesBulk(params" },
        { binding: "WhisperClient.memory.addBulk", token: "addBulk: (params) => this.memoryModule.addBulk(params)" },
      ],
      mcp_primary: [],
      mcp_compat: [],
    },
  }),
  defineOperation({
    id: "memory.extract",
    request_schema: { type: "object", properties: { project: "string", message: "string?" } },
    response_schema: { type: "object", properties: { explicit: "array?", implicit: "array?" } },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: { classification: "customer-memory", input_sensitivity: "high", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "ingest",
    security_profile: "session_capture",
    surfaces: {
      http: [
        { method: "POST", route: "/v1/memory/extract", status: "canonical" },
        { method: "POST", route: "/v1/memory/extract/session", status: "canonical" },
      ],
      sdk: [
        { binding: "WhisperContext.extractMemories", token: "async extractMemories(params" },
        { binding: "WhisperContext.extractSessionMemories", token: "async extractSessionMemories(params" },
      ],
      mcp_primary: [],
      mcp_compat: [],
    },
  }),
  defineOperation({
    id: "memory.profile_views",
    request_schema: { type: "object", properties: { project: "string", user_id: "string?", session_id: "string?" } },
    response_schema: { type: "object", properties: { memories: "array", count: "number" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "customer-memory", input_sensitivity: "high", output_sensitivity: "high", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: {
      http: [
        { method: "GET", route: "/v1/memory/session/:sessionId", status: "canonical" },
        { method: "GET", route: "/v1/memory/profile/:userId", status: "canonical" },
        { method: "GET", route: "/v1/memories", status: "compat", replacement: "/v1/memory/profile/:userId or /v1/memory/session/:sessionId" },
      ],
      sdk: [
        { binding: "WhisperContext.getSessionMemories", token: "async getSessionMemories(params" },
        { binding: "WhisperContext.getUserProfile", token: "async getUserProfile(params" },
        { binding: "WhisperClient.memory.getSessionMemories", token: "getSessionMemories: (params) => this.memoryModule.getSessionMemories(params)" },
        { binding: "WhisperClient.memory.getUserProfile", token: "getUserProfile: (params) => this.memoryModule.getUserProfile(params)" },
      ],
      mcp_primary: [],
      mcp_compat: [],
    },
  }),
  defineOperation({
    id: "memory.graph",
    request_schema: { type: "object", properties: { project: "string", user_id: "string?", session_id: "string?" } },
    response_schema: { type: "object", properties: { nodes: "array?", edges: "array?" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "customer-memory", input_sensitivity: "high", output_sensitivity: "high", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: {
      http: [
        { method: "GET", route: "/v1/memory/graph", status: "canonical" },
        { method: "GET", route: "/v1/memory/graph/conversation/:sessionId", status: "canonical" },
      ],
      sdk: [
        { binding: "WhisperContext.getMemoryGraph", token: "async getMemoryGraph(params" },
        { binding: "WhisperContext.getConversationGraph", token: "async getConversationGraph(params" },
      ],
      mcp_primary: [],
      mcp_compat: [],
    },
  }),
  defineOperation({
    id: "memory.versions",
    request_schema: { type: "object", properties: { memory_id: "string" } },
    response_schema: { type: "object", properties: { versions: "array", count: "number" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "customer-memory", input_sensitivity: "high", output_sensitivity: "high", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: {
      http: [
        { method: "GET", route: "/v1/memory/jobs/:jobId", status: "canonical" },
        { method: "GET", route: "/v1/memory/:memoryId/versions", status: "canonical" },
      ],
      sdk: [{ binding: "WhisperContext.getMemoryVersions", token: "async getMemoryVersions(memoryId" }],
      mcp_primary: [],
      mcp_compat: [],
    },
  }),
  defineOperation({
    id: "memory.mutations",
    request_schema: { type: "object", properties: { memory_id: "string", content: "string?" } },
    response_schema: { type: "object", properties: { success: "boolean" } },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: { classification: "customer-memory", input_sensitivity: "high", output_sensitivity: "low", logging: "redacted" },
    rate_limit_profile: "mutation",
    security_profile: "delete_admin",
    surfaces: {
      http: [
        { method: "PUT", route: "/v1/memory/:memoryId", status: "canonical" },
        { method: "DELETE", route: "/v1/memory/:memoryId", status: "canonical" },
        { method: "POST", route: "/v1/memory/:memoryId/confirm", status: "canonical" },
        { method: "POST", route: "/v1/memory/bulk-delete", status: "canonical" },
        { method: "PUT", route: "/v1/memories/:id", status: "compat", replacement: "/v1/memory/:memoryId" },
        { method: "DELETE", route: "/v1/memories/:id", status: "compat", replacement: "/v1/memory/:memoryId" },
      ],
      sdk: [
        { binding: "WhisperContext.updateMemory", token: "async updateMemory(" },
        { binding: "WhisperContext.deleteMemory", token: "async deleteMemory(memoryId" },
        { binding: "WhisperClient.memory.update", token: "update: (memoryId, params) => this.memoryModule.update(memoryId, params)" },
        { binding: "WhisperClient.memory.delete", token: "delete: (memoryId) => this.memoryModule.delete(memoryId)" },
      ],
      mcp_primary: [],
      mcp_compat: [{ tool: "memory.forget" }, { tool: "forget" }],
    },
  }),
  defineOperation({
    id: "context.learn",
    request_schema: {
      type: "object",
      description: "Unified learning entry for conversation capture, direct text ingestion, and source-based knowledge ingestion.",
      required: ["mode"],
      properties: {
        mode: "conversation|text|source",
        project: "string?",
        user_id: "string?",
        session_id: "string?",
        messages: "array?",
        title: "string?",
        content: "string?",
        metadata: "object?",
        tags: "array?",
        namespace: "string?",
        type: "github|web|playwright|pdf|local|slack|video?",
        owner: "string?",
        repo: "string?",
        branch: "string?",
        paths: "array?",
        url: "string?",
        file_path: "string?",
        path: "string?",
        channel_ids: "array?",
        since: "string?",
        token: "string?",
        auth_ref: "string?",
        platform: "youtube|loom|generic?",
        language: "string?",
        options: "object?",
      },
      validation: [
        "mode=conversation requires session_id and messages[].",
        "mode=text requires title and content.",
        "mode=source requires type and the source-specific identity fields for that type.",
        "When conversation learning omits user_id, the implementation falls back to session-only scope.",
      ],
    },
    response_schema: {
      type: "object",
      properties: {
        success: "boolean",
        mode: "conversation|text|source",
        project: "string",
        scope_mode: "user_session|session_only?",
        memories_created: "number?",
        relations_created: "number?",
        memories_invalidated: "number?",
        status: "string?",
        job_id: "string?",
        source_id: "string?",
        index_started: "boolean?",
      },
    },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: { classification: "knowledge-ingest", input_sensitivity: "high", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "ingest",
    security_profile: "knowledge_ingest",
    security_overrides: {
      user_scope: "optional",
      audit_required: true,
      local_filesystem_risk: "allowlist-only",
    },
    surfaces: {
      http: [{ method: "POST", route: "/v1/learn", status: "canonical" }],
      sdk: [
        { binding: "WhisperContext.learn", token: "async learn(params" },
        { binding: "WhisperClient.learn", token: "async learn(params" },
        { binding: "Whisper.learn", token: "async learn(params" },
      ],
      mcp_primary: [{ tool: "learn" }],
      mcp_compat: [
        { tool: "context.add_text" },
        { tool: "context.add_document" },
        { tool: "context.add_source" },
        { tool: "memory.ingest_conversation" },
      ],
    },
  }),
  defineOperation({
    id: "context.learn_text",
    request_schema: { type: "object", properties: { project: "string?", content: "string", title: "string?" } },
    response_schema: { type: "object", properties: { ingested: "number" } },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: { classification: "knowledge-ingest", input_sensitivity: "high", output_sensitivity: "low", logging: "redacted" },
    rate_limit_profile: "ingest",
    security_profile: "knowledge_ingest",
    surfaces: {
      http: [{ method: "POST", route: "/v1/projects/:projectId/ingest", status: "canonical" }],
      sdk: [
        { binding: "WhisperContext.ingest", token: "async ingest(" },
        { binding: "WhisperContext.addContext", token: "async addContext(params" },
      ],
      mcp_primary: [{ tool: "learn", mode: "text" }],
      mcp_compat: [{ tool: "context.add_text" }, { tool: "context.add_document" }],
    },
  }),
  defineOperation({
    id: "context.learn_source",
    request_schema: { type: "object", properties: { project: "string", url: "string?", owner: "string?", repo: "string?", path: "string?" } },
    response_schema: { type: "object", properties: { source_id: "string", status: "string", job_id: "string?" } },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: { classification: "knowledge-ingest", input_sensitivity: "high", output_sensitivity: "low", logging: "redacted" },
    rate_limit_profile: "ingest",
    security_profile: "knowledge_ingest",
    surfaces: {
      http: [
        { method: "POST", route: "/v1/projects/:projectId/sources", status: "canonical" },
        { method: "POST", route: "/v1/sources/:sourceId/sync", status: "canonical" },
        { method: "GET", route: "/v1/sources/:sourceId/status", status: "canonical" },
      ],
      sdk: [
        { binding: "WhisperContext.createCanonicalSource", token: "async createCanonicalSource(" },
        { binding: "WhisperContext.addSource", token: "async addSource(" },
      ],
      mcp_primary: [{ tool: "learn", mode: "source" }],
      mcp_compat: [{ tool: "context.add_source" }, { tool: "context.source_status" }],
    },
  }),
  defineOperation({
    id: "context.index",
    request_schema: {
      type: "object",
      description: "High-level bulk index endpoint that creates sources, triggers sync, and optionally returns a portable bundle.",
      required: ["sources"],
      properties: {
        project: "string?",
        sources: "array",
        auto_index: "boolean?",
        return_bundle: "boolean?",
        bundle: "object?",
      },
      validation: [
        "If project is omitted, the server uses WHISPER_PROJECT when available.",
        "sources[] items must include a connector type and its identity/config fields.",
      ],
    },
    response_schema: {
      type: "object",
      properties: {
        success: "boolean",
        project: "object",
        results: "array",
        bundle: "object?",
        bundle_endpoint: "string",
      },
    },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: { classification: "knowledge-ingest", input_sensitivity: "high", output_sensitivity: "high", logging: "redacted" },
    rate_limit_profile: "ingest",
    security_profile: "knowledge_ingest",
    security_overrides: {
      user_scope: "optional",
      audit_required: true,
      local_filesystem_risk: "allowlist-only",
    },
    surfaces: {
      http: [{ method: "POST", route: "/v1/index", status: "canonical" }],
      sdk: [],
      mcp_primary: [],
      mcp_compat: [],
    },
  }),
  defineOperation({
    id: "context.index_bundle",
    request_schema: {
      type: "object",
      description: "Export indexed project data into a single JSON bundle with checksum.",
      required: ["project"],
      properties: {
        project: "string",
        include: "object?",
        limits: "object?",
        redact_secrets: "boolean?",
      },
    },
    response_schema: { type: "object", properties: { success: "boolean", bundle: "object" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "share_export", input_sensitivity: "high", output_sensitivity: "high", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "share_export",
    surfaces: {
      http: [{ method: "POST", route: "/v1/index/bundle", status: "canonical" }],
      sdk: [],
      mcp_primary: [],
      mcp_compat: [],
    },
  }),
  defineOperation({
    id: "context.share",
    request_schema: { type: "object", properties: { project: "string", session_id: "string", expiry_days: "number?" } },
    response_schema: { type: "object", properties: { share_id: "string", share_url: "string", expires_at: "string" } },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: { classification: "shared-context", input_sensitivity: "high", output_sensitivity: "high", logging: "redacted" },
    rate_limit_profile: "mutation",
    security_profile: "share_export",
    surfaces: {
      http: [
        { method: "POST", route: "/v1/context/share", status: "canonical" },
        { method: "GET", route: "/v1/context/shared/:shareId", status: "canonical" },
        { method: "POST", route: "/v1/context/resume", status: "canonical" },
      ],
      sdk: [
        { binding: "WhisperContext.createSharedContext", token: "async createSharedContext(params" },
        { binding: "WhisperContext.loadSharedContext", token: "async loadSharedContext(shareId" },
        { binding: "WhisperContext.resumeFromSharedContext", token: "async resumeFromSharedContext(params" },
      ],
      mcp_primary: [{ tool: "share_context" }],
      mcp_compat: [{ tool: "context.share" }],
    },
  }),
  defineOperation({
    id: "research.oracle",
    request_schema: { type: "object", properties: { project: "string", query: "string", mode: "search|research?" } },
    response_schema: { type: "object", properties: { answer: "string?", results: "array?" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "knowledge-base", input_sensitivity: "medium", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: {
      http: [{ method: "POST", route: "/v1/oracle/search", status: "canonical" }],
      sdk: [{ binding: "WhisperContext.oracleSearch", token: "async oracleSearch(params" }],
      mcp_primary: [{ tool: "research" }],
      mcp_compat: [{ tool: "research.oracle" }],
    },
  }),
  defineOperation({
    id: "code.search_text",
    request_schema: { type: "object", properties: { query: "string", path: "string?" } },
    response_schema: { type: "object", properties: { results: "array" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "code-search", input_sensitivity: "medium", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: {
      http: [{ method: "POST", route: "/v1/search/files", status: "canonical" }],
      sdk: [],
      mcp_primary: [{ tool: "grep" }],
      mcp_compat: [{ tool: "code.search_text" }],
    },
  }),
  defineOperation({
    id: "code.search_semantic",
    request_schema: { type: "object", properties: { query: "string", documents: "array?" } },
    response_schema: { type: "object", properties: { results: "array", diagnostics: "object?", warnings: "array?" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "code-search", input_sensitivity: "medium", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: {
      http: [{ method: "POST", route: "/v1/search/semantic", status: "canonical" }],
      sdk: [{ binding: "WhisperContext.semanticSearch", token: "async semanticSearch(params" }],
      mcp_primary: [{ tool: "search_code" }],
      mcp_compat: [{ tool: "code.search_semantic" }, { tool: "code.semantic_documents" }],
    },
  }),
  defineOperation({
    id: "local.file_read",
    request_schema: { type: "object", properties: { path: "string", start_line: "number?", end_line: "number?" } },
    response_schema: { type: "object", properties: { content: "string" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "workspace" },
    privacy: { classification: "local-filesystem", input_sensitivity: "high", output_sensitivity: "high", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "knowledge_ingest",
    security_overrides: { abuse_profile: "query", destructive: false },
    surfaces: {
      http: [],
      sdk: [],
      mcp_primary: [{ tool: "read" }],
      mcp_compat: [],
    },
  }),
  defineOperation({
    id: "local.tree",
    request_schema: { type: "object", properties: { path: "string?", max_depth: "number?" } },
    response_schema: { type: "object", properties: { tree: "string" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "workspace" },
    privacy: { classification: "local-filesystem", input_sensitivity: "medium", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    security_overrides: { local_filesystem_risk: "read-only" },
    surfaces: {
      http: [],
      sdk: [],
      mcp_primary: [{ tool: "explore" }],
      mcp_compat: [],
    },
  }),
  defineOperation({
    id: "index.workspace_resolve",
    request_schema: { type: "object", properties: { path: "string?" } },
    response_schema: { type: "object", properties: { workspace_id: "string", root_path: "string?", project_ref: "string?", project_id: "string?", resolved_by: "string?", health: "string?", warnings: "array?" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "workspace" },
    privacy: { classification: "workspace-metadata", input_sensitivity: "low", output_sensitivity: "low", logging: "standard" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: { http: [], sdk: [], mcp_primary: [], mcp_compat: [{ tool: "index.workspace_resolve" }, { tool: "index" }] },
  }),
  defineOperation({
    id: "index.workspace_status",
    request_schema: { type: "object", properties: { path: "string?" } },
    response_schema: { type: "object", properties: { workspace_id: "string", root_path: "string?", project_ref: "string?", project_id: "string?", health: "string?", warnings: "array?", recommended_next_calls: "array?" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "workspace" },
    privacy: { classification: "workspace-metadata", input_sensitivity: "low", output_sensitivity: "low", logging: "standard" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: { http: [], sdk: [], mcp_primary: [], mcp_compat: [{ tool: "index.workspace_status" }, { tool: "index" }] },
  }),
  defineOperation({
    id: "index.workspace_run",
    request_schema: { type: "object", properties: { path: "string?", mode: "full|incremental?" } },
    response_schema: { type: "object", properties: { indexed_files: "number" } },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "workspace" },
    privacy: { classification: "workspace-index", input_sensitivity: "medium", output_sensitivity: "low", logging: "redacted" },
    rate_limit_profile: "mutation",
    security_profile: "knowledge_ingest",
    surfaces: { http: [], sdk: [], mcp_primary: [], mcp_compat: [{ tool: "index.workspace_run" }, { tool: "index" }] },
  }),
  defineOperation({
    id: "index.auto_repair",
    request_schema: {
      type: "object",
      properties: {
        path: "string?",
        workspace_id: "string?",
        project: "string?",
        apply: "boolean?",
        repair_scope: "safe|full?",
        allow_restart_hint: "boolean?",
      },
    },
    response_schema: {
      type: "object",
      properties: {
        root_cause_code: "none|missing_api_key|no_project_bound|mode_mismatch_remote_local_ingest|workspace_unindexed|project_bound_no_repo_source|project_unverified|project_repo_source_stale|semantic_backend_unavailable|local_fallback_active",
        actions_attempted: "array",
        actions_succeeded: "array",
        actions_failed: "array",
        restart_required: "boolean",
        verification_passed: "boolean",
        status_label: "healthy|degraded_auto_repairing|needs_user_action|blocked",
        status_action: "none|run_auto_repair|restart_client|reauth|add_source|reindex",
        action_required: "boolean",
        recommended_next_calls: "array?",
        diagnostics: "object?",
      },
    },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "workspace" },
    privacy: { classification: "workspace-index", input_sensitivity: "medium", output_sensitivity: "low", logging: "redacted" },
    rate_limit_profile: "mutation",
    security_profile: "knowledge_ingest",
    surfaces: { http: [], sdk: [], mcp_primary: [{ tool: "fix" }], mcp_compat: [{ tool: "index.auto_repair" }] },
  }),
  defineOperation({
    id: "index.local_scan_ingest",
    request_schema: { type: "object", properties: { path: "string?", glob: "string?" } },
    response_schema: { type: "object", properties: { ingested: "number", skipped: "array?" } },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "workspace" },
    privacy: { classification: "local-filesystem", input_sensitivity: "high", output_sensitivity: "low", logging: "redacted" },
    rate_limit_profile: "ingest",
    security_profile: "knowledge_ingest",
    security_overrides: { local_filesystem_risk: "allowlist-only", audit_required: true },
    surfaces: { http: [], sdk: [], mcp_primary: [], mcp_compat: [{ tool: "index.local_scan_ingest" }] },
  }),
  defineOperation({
    id: "index.autosubscribe_deps",
    request_schema: { type: "object", properties: { project: "string", source_type: "string" } },
    response_schema: { type: "object", properties: { discovered: "number", indexed: "number" } },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: { classification: "dependency-ingest", input_sensitivity: "medium", output_sensitivity: "low", logging: "redacted" },
    rate_limit_profile: "ingest",
    security_profile: "knowledge_ingest",
    surfaces: {
      http: [{ method: "POST", route: "/v1/autosubscribe", status: "canonical" }],
      sdk: [{ binding: "WhisperContext.autosubscribe", token: "async autosubscribe(params" }],
      mcp_primary: [],
      mcp_compat: [{ tool: "index.autosubscribe_deps" }],
    },
  }),
  defineOperation({
    id: "context.get_relevant",
    status: "compat",
    request_schema: { type: "object", properties: { question: "string", top_k: "number?" } },
    response_schema: {
      type: "object",
      properties: {
        evidence: "array",
        context: "string?",
        trust_state: "object?",
        warnings: "array?",
        recommended_next_calls: "array?",
        semantic_status: "ok|adaptive|failed?",
        fallback_mode: "none|adaptive_threshold|lexical_rescue|lexical_backend?",
        recommended_fixes: "array?",
        status_label: "healthy|degraded_auto_repairing|needs_user_action|blocked?",
        status_action: "none|run_auto_repair|restart_client|reauth|add_source|reindex?",
        action_required: "boolean?",
        diagnostics: "object?",
      },
    },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "knowledge-base", input_sensitivity: "medium", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    deprecation: { status: "deprecated", replacement: "context.query", note: "Use context.query for canonical retrieval behavior." },
    surfaces: { http: [], sdk: [], mcp_primary: [], mcp_compat: [{ tool: "context.get_relevant" }] },
  }),
  defineOperation({
    id: "context.claim_verify",
    request_schema: { type: "object", properties: { claim: "string" } },
    response_schema: { type: "object", properties: { verdict: "string", evidence: "array", trust_state: "object?", warnings: "array?", recommended_next_calls: "array?" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "knowledge-base", input_sensitivity: "medium", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: { http: [], sdk: [], mcp_primary: [], mcp_compat: [{ tool: "context.claim_verify" }] },
  }),
  defineOperation({
    id: "context.evidence_answer",
    request_schema: { type: "object", properties: { question: "string", constraints: "object?" } },
    response_schema: { type: "object", properties: { status: "string", answer: "string?", trust_state: "object?", warnings: "array?", recommended_next_calls: "array?" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "knowledge-base", input_sensitivity: "medium", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: { http: [], sdk: [], mcp_primary: [], mcp_compat: [{ tool: "context.evidence_answer" }] },
  }),
  defineOperation({
    id: "context.list_projects",
    request_schema: { type: "object", properties: {} },
    response_schema: { type: "object", properties: { projects: "array" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "org" },
    privacy: { classification: "project-metadata", input_sensitivity: "low", output_sensitivity: "low", logging: "standard" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: {
      http: [
        { method: "POST", route: "/v1/projects", status: "canonical" },
        { method: "GET", route: "/v1/projects", status: "canonical" },
        { method: "GET", route: "/v1/projects/:id", status: "canonical" },
        { method: "DELETE", route: "/v1/projects/:id", status: "canonical" },
      ],
      sdk: [
        { binding: "WhisperContext.createProject", token: "async createProject(params" },
        { binding: "WhisperContext.listProjects", token: "async listProjects()" },
        { binding: "WhisperContext.getProject", token: "async getProject(id" },
        { binding: "WhisperContext.deleteProject", token: "async deleteProject(id" },
      ],
      mcp_primary: [],
      mcp_compat: [{ tool: "context.list_projects" }],
    },
  }),
  defineOperation({
    id: "context.list_sources",
    request_schema: { type: "object", properties: { project: "string?" } },
    response_schema: { type: "object", properties: { sources: "array" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "source-metadata", input_sensitivity: "low", output_sensitivity: "low", logging: "standard" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: { http: [{ method: "GET", route: "/v1/projects/:projectId/sources", status: "canonical" }], sdk: [], mcp_primary: [], mcp_compat: [{ tool: "context.list_sources" }] },
  }),
  defineOperation({
    id: "memory.search_sota",
    request_schema: { type: "object", properties: { query: "string", project: "string?", scope: "personal|shared_project?", user_id: "string?", session_id: "string?", question_date: "string?" } },
    response_schema: { type: "object", properties: { memories: "array" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "customer-memory", input_sensitivity: "high", output_sensitivity: "high", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: { http: [], sdk: [{ binding: "WhisperContext.searchMemoriesSOTA", token: "searchMemoriesSOTA(" }], mcp_primary: [], mcp_compat: [{ tool: "memory.search_sota" }] },
  }),
  defineOperation({
    id: "memory.consolidate",
    request_schema: { type: "object", properties: { project: "string?", dry_run: "boolean?" } },
    response_schema: { type: "object", properties: { clusters_found: "number?" } },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: { classification: "customer-memory", input_sensitivity: "high", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "mutation",
    security_profile: "memory_write",
    surfaces: { http: [], sdk: [{ binding: "WhisperContext.consolidateMemories", token: "async consolidateMemories(params" }], mcp_primary: [], mcp_compat: [{ tool: "memory.consolidate" }] },
  }),
  defineOperation({
    id: "memory.forget",
    request_schema: { type: "object", properties: { project: "string?", scope: "personal|shared_project?", user_id: "string?", session_id: "string?", target: "object", reason: "string?" } },
    response_schema: { type: "object", properties: { success: "boolean" } },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: { classification: "customer-memory", input_sensitivity: "high", output_sensitivity: "low", logging: "redacted" },
    rate_limit_profile: "mutation",
    security_profile: "delete_admin",
    surfaces: { http: [], sdk: [], mcp_primary: [], mcp_compat: [{ tool: "memory.forget" }] },
  }),
  defineOperation({
    id: "context.export_bundle",
    request_schema: { type: "object", properties: { project: "string?" } },
    response_schema: { type: "object", properties: { bundle: "object" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "project" },
    privacy: { classification: "portable-context", input_sensitivity: "high", output_sensitivity: "high", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "share_export",
    surfaces: { http: [], sdk: [], mcp_primary: [], mcp_compat: [{ tool: "context.export_bundle" }] },
  }),
  defineOperation({
    id: "context.import_bundle",
    request_schema: { type: "object", properties: { bundle: "object" } },
    response_schema: { type: "object", properties: { imported: "boolean" } },
    auth: { type: "api_key", scopes: ["write"], tenant_scope: "project" },
    privacy: { classification: "portable-context", input_sensitivity: "high", output_sensitivity: "high", logging: "redacted" },
    rate_limit_profile: "mutation",
    security_profile: "share_export",
    surfaces: { http: [], sdk: [], mcp_primary: [], mcp_compat: [{ tool: "context.import_bundle" }] },
  }),
  defineOperation({
    id: "context.diff",
    request_schema: { type: "object", properties: { anchor: "object?" } },
    response_schema: { type: "object", properties: { changes: "array?" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "workspace" },
    privacy: { classification: "workspace-metadata", input_sensitivity: "medium", output_sensitivity: "medium", logging: "redacted" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: { http: [], sdk: [], mcp_primary: [], mcp_compat: [{ tool: "context.diff" }] },
  }),
  defineOperation({
    id: "context.cost_summary",
    request_schema: { type: "object", properties: { project: "string?", days: "number?" } },
    response_schema: { type: "object", properties: { total_cost: "number?" } },
    auth: { type: "api_key", scopes: ["read"], tenant_scope: "org" },
    privacy: { classification: "billing-metadata", input_sensitivity: "low", output_sensitivity: "medium", logging: "standard" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    surfaces: { http: [], sdk: [{ binding: "WhisperContext.getCostSummary", token: "async getCostSummary(params" }], mcp_primary: [], mcp_compat: [{ tool: "context.cost_summary" }] },
  }),
  defineOperation({
    id: "contract.meta",
    request_schema: { type: "object", properties: {} },
    response_schema: {
      type: "object",
      properties: {
        contract_version: "string",
        active_surfaces: "array",
        mcp_primary_verbs: "array",
        migration_window_days: "number",
        removal_policy: "string",
        sdk_legacy: "object",
        deprecated_routes: "array",
      },
    },
    auth: { type: "none", scopes: [], tenant_scope: "none" },
    privacy: { classification: "public-metadata", input_sensitivity: "low", output_sensitivity: "low", logging: "standard" },
    rate_limit_profile: "query",
    security_profile: "retrieval",
    security_overrides: { auth_type: "none", tenant_scope: "none", user_scope: "none" },
    surfaces: { http: [{ method: "GET", route: "/v1/contracts/meta", status: "canonical" }], sdk: [], mcp_primary: [], mcp_compat: [] },
  }),
]);

export function getContractById(id) {
  return CONTRACT_REGISTRY.find((entry) => entry.id === id);
}

export function collectMcpTools(kind) {
  const tools = new Set();
  for (const entry of CONTRACT_REGISTRY) {
    const surfaces = entry.surfaces?.[kind] || [];
    for (const surface of surfaces) {
      if (surface?.tool && MCP_RUNTIME_TOOLSET.includes(surface.tool)) {
        tools.add(surface.tool);
      }
    }
  }
  return Array.from(tools).sort();
}

export function collectHttpRoutes() {
  const routes = [];
  for (const entry of CONTRACT_REGISTRY) {
    for (const route of entry.surfaces?.http || []) {
      routes.push({ ...route, id: entry.id });
    }
  }
  return routes;
}
